# Generated by Django 5.0.14 on 2026-05-30 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('actor_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'Hr'), ('MANAGERIAL', 'Managerial'), ('CULTURE_FIT', 'Culture Fit'), ('FINAL_ROUND', 'Final Round')], max_length=20)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person'), ('PHONE', 'Phone')], max_length=20)),
                ('date', models.DateTimeField()),
                ('duration_min', models.PositiveIntegerField(default=60)),
                ('interviewer', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
