# Generated by Django 5.0.14 on 2026-06-17 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='InterviewCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'Hr'), ('MANAGERIAL', 'Managerial'), ('CULTURE_FIT', 'Culture Fit'), ('FINAL_ROUND', 'Final Round')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Interview Categories',
                'unique_together': {('type', 'name')},
            },
        ),
    ]
