# Generated by Django 5.0.14 on 2026-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_handler',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
