# Generated by Django 5.0.14 on 2026-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_interview_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
