# Generated by Django 5.0.14 on 2026-06-18 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_recruiter_user_can_view_recruiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recruiters', to=settings.AUTH_USER_MODEL),
        ),
    ]
